spring:
  application:
    name: Naengu

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

logging:
  level:
    root: INFO
    com.potatoes.Naengu: INFO
    org.hibernate.SQL: debug
